"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

import math


def triangle_number(n: int) -> int:
    return sum(list(range(n + 1)))


def get_divisors(n: int) -> int:
    count = 0
    for i in range(1, int(math.sqrt(n)) + 1):
        if n % i == 0:
            count += 1
            if i != n // i:
                count += 1
    return count


def solution(nmax: int = 500):
    divisors = 1
    i = 1
    while divisors < nmax:
        tn = triangle_number(i)
        divisors = get_divisors(tn)
        i += 1
    return triangle_number(i - 1)


if __name__ == "__main__":
    print(solution(nmax=500))
